### ISSUE TITLE
Import Fail

### ISSUE THREAD

**Issue by alexroan** [alphachainio/chainlink_feeds#1]
Following the install instructions

```
pip3 install chainlink_feeds
```

the import statement returns the following error:

```
Traceback (most recent call last):
  File "quick.py", line 1, in <module>
    from chainlink_feeds import ChainlinkFeeds
ModuleNotFoundError: No module named 'chainlink_feeds'
```

python version 3.8.5

**Comment by PatrickAlphaC** [comment]
Can you run:
`pip3 freeze` and see if `chainlink_feeds` is in there?

And then run a `which pip3` and a `which python`

You might be running python2.7 but installing it on python3.8.5

**Comment by alexroan** [comment]
I get `chainlink-feeds==0.2.3` with `pip3 freeze`

**Comment by PatrickAlphaC** [comment]
Oh, I'm looking to see if your pip3 and python are pointing to the same dir. Not sure why else they might be different.

**Comment by mattory029** [comment]
Use pip  install to install the  package. chainlink-feeds==0.2.3 are listed in PIP freeze, but import < package > causes the error:  no module named < package >.   the site packages folder contains only the dist_info folder.

**Comment by PatrickAlphaC** [comment]
Thanks all! Could you try again? I've updated the readme as well, slightly different package placement
