### ISSUE TITLE
pip install . creates only the dist-info not the package

### ISSUE THREAD

**Issue by mattory029** [alphachainio/chainlink_feeds#2]
The package name is listed in pip freeze but import <package> results in an error No module named <package>. Also the site-packages folder does only contain a dist-info folder. 

Try many computers,  get the same result

 https://www.tfzx.net/article/1416661.html

**Comment by PatrickAlphaC** [comment]
Wow, thanks so much for this! I was banging my head trying to figure out what was going on.

Could you try it now? I also updated the readme

**Comment by mattory029** [comment]
running smoothly，thanks!

**Comment by mattory029** [comment]
Running smoothly!  Thanks!

**Comment by PatrickAlphaC** [comment]
Great, thank you!
